const userConstants = {
  FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
};

export default userConstants;
